# Generated by Django 3.0.7 on 2020-07-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedb',
            name='category',
            field=models.ManyToManyField(to='home.Category', verbose_name='دسته بندی'),
        ),
    ]
