# Generated by Django 3.0.7 on 2020-07-23 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homedb_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homedb',
            options={'ordering': ['-publish'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='home.Category', verbose_name='زیر دسته'),
        ),
        migrations.AlterField(
            model_name='homedb',
            name='category',
            field=models.ManyToManyField(related_name='article', to='home.Category', verbose_name='دسته بندی'),
        ),
    ]
